repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Black formatter
        files: ^main/
        stages: [pre-commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sorting imports
        files: ^main/
        stages: [pre-commit]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Security Linter
        files: ^main/
        stages: [pre-commit]
