general:
  seed: 42
data_loader:
  path: "data/ml-100k"
  sub_paths: ["data", "user", "item"]
data_preparation:
  rating_conversion:
    0: [1, 2, 3]
    1: [4]
    2: [5]
  rating_flag:
    negative: [0]
    positive: [1, 2]
train:
  path: "main/artifacts"
  negative_sample:
    popular: 15
    covisit: 10
  ranker:
    XGBRanker:
      booster: "gbtree"
      objective: "rank:pairwise"
      eval_metric: "ndcg"
      random_state: 42
      verbosity: 0
      learning_rate: 0.07884126564776513
      gamma: 0.5808361216819946
      max_depth: 14
      sub_sample: 0.8005575058716043
      n_estimators: 298
      